[theme]
base = "dark"
primaryColor = "#3987e5"
backgroundColor = "#121211"
secondaryBackgroundColor = "#1a1a19"
textColor = "#ffffff"
font = "sans serif"

[server]
headless = true
runOnSave = false

[browser]
gatherUsageStats = false
